package se.lexicon;

import se.lexicon.dao.UserDao;
import se.lexicon.dao.UserDaoImpl;
import se.lexicon.model.User;
import se.lexicon.util.PasswordGenerator;

import java.util.Scanner;

public class UserRegistration {
    private static final UserDao userDao = new UserDaoImpl();
    private static final Scanner scanner = new Scanner(System.in);

    public static void register() {
        System.out.println("Enter your desired username: ");
        String username = scanner.nextLine();

        // Check if username already exists
        if (userDao.findByUsername(username) != null) {
            System.out.println("Username already exists. Please choose a different username.");
            return;
        }

        // Generate password
        String password = PasswordGenerator.generateRandomPassword();

        // Create User object without an ID since it's generated by the database
        User user = new User(username, password, false); // Pass the correct parameters for the constructor

        // Save user to database
        userDao.save(user);

        // Display generated password to user
        System.out.println("Registration successful! Your password is: " + password);
    }
}
